### PR TITLE
Fix #51 Add AWS lambda support to nodecloud

### LINKED ISSUE #51: Serverless Support to nodecloud -- AWS Lambda
# This is a Feature Proposal

## Description

For bug reports:
* What went wrong?
* What did you expect should have happened?
* What was the config you used?
* What stacktrace or error message from your provider did you see?

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

This will add support to serverless service integration with nodecloud for AWS.
* If there is additional config how would it look

Similar or dependent issues:

## Additional Data

* ***Operating System***:
* ***Stack Trace***:
* ***Provider Error messages***:

### PR DESCRIPTION
**Pull request by raju249**
## What did you implement:

Closes #51 

## How did you implement it:
Used aws nodejs sdk to add support for AWS Lambda

## How can we verify it:
Run example code in `examples\serverless\aws-lambda.js`

## Todos:

- [x] Write tests
- [ ] Write documentation
- [ ] Fix linting errors
- [ ] Make sure code coverage hasn't dropped
- [ ] Provide verification config / commands / resources
- [ ] Enable "Allow edits from maintainers" for this PR
- [ ] Update the messages below

***Is this ready for review?:*** YES
***Is it a breaking change?:*** NO

### CODE REVIEW

**Review by rajikaimal — COMMENTED** [review]
Can you add an example to `/docs` ?
PR looks solid.

**Comment by raju249** [comment]
Sure. Having lunch right now, will do it asap.
Thanks 😊

**Comment by rajikaimal** [comment]
Cool, no hurry 😄

File: lib/core/aws/provider.js [hunk 1]
```diff
@@ -42,6 +43,7 @@ class AWS {
       rdbms: this.RDS,
       nosql: this.DynamoDB,
       iam: this.IAM,
+      lambda: this.Lambda,
```
Comment (rehrumesh) [inline lib/core/aws/provider.js]: we should rename `lambda` to something like `function` or `faas` or anything which generalize the term. Otherwise, we will end up writing provider specific terms which is not healthy for the project. For example Azure use `Azure Functions`, Google use `Google Cloud Functions` for the same functionality. @rajikaimal WDYT?

**Comment by raju249** [comment]
Let's go with serverless ?

**Comment by rehrumesh** [comment]
Though lambda plays a big role in serverless computing paradigm, Lambda (or FaaS) is not the only thing to be count as serverless. So I disagree there.

**Comment by raju249** [comment]
I see.
Functions seems good to me then.

**Comment by raju249** [comment]
@rajikaimal @rehrumesh 
I think we should go ahead with `nodecloud.functions` 
Let me know what you think

**Comment by raju249** [comment]
Any suggestions @rajikaimal @rehrumesh ?

**Comment by rajikaimal** [comment]
functions seems okay

**Comment by raju249** [comment]
Sure, changing it then 😄

**Comment by raju249** [comment]
@rajikaimal @rehrumesh 
I changed the name from `lambda` to `functions`
